### ISSUE TITLE
error: redefinition of ‘vid_.. errors

### ISSUE THREAD

**Issue by gyakovlev** [groeck/it87#86]
fails to compile after 905a3a095d49ef9f6eea5ec1b0bc21e3c6901b9e
kernel is custom 4.16.8-gentoo
gcc is 7.3
CONFIG_HWMON_VID is not set, so it's that oddball config you've mentioned =)

since one can't select CONFIG_HWMON_VID directly I had to enable some other module that auto-selects CONFIG_HWMON_VID and it builds fine after that.

```shell-session
In file included from /tmp/portage/sys-kernel/it87-9999/work/it87-9999/it87.c:79:0:
/tmp/portage/sys-kernel/it87-9999/work/it87-9999/compat.h:69:5: error: redefinition of ‘vid_from_reg’
 int vid_from_reg(int val, u8 vrm)
     ^~~~~~~~~~~~
/tmp/portage/sys-kernel/it87-9999/work/it87-9999/compat.h:15:5: note: previous definition of ‘vid_from_reg’ was here
 int vid_from_reg(int val, u8 vrm)
     ^~~~~~~~~~~~
/tmp/portage/sys-kernel/it87-9999/work/it87-9999/compat.h:74:4: error: redefinition of ‘vid_which_vrm’
 u8 vid_which_vrm(void)
    ^~~~~~~~~~~~~
/tmp/portage/sys-kernel/it87-9999/work/it87-9999/compat.h:20:4: note: previous definition of ‘vid_which_vrm’ was here
 u8 vid_which_vrm(void)
    ^~~~~~~~~~~~~
```

**Comment by groeck** [comment]
Patch reverted. Thanks for the note.
